import os

DEFAULT_LABELS = [
    "person",
    "man",
    "woman",
    "child",
    "crowd",
    "bicycle",
    "motorcycle",
    "car",
    "truck",
    "bus",
    "train",
    "airplane",
    "boat",
    "bridge",
    "road",
    "highway",
    "street",
    "sidewalk",
    "crosswalk",
    "traffic light",
    "stop sign",
    "building",
    "skyscraper",
    "house",
    "apartment",
    "tower",
    "stadium",
    "factory",
    "warehouse",
    "garage",
    "parking lot",
    "tunnel",
    "overpass",
    "tree",
    "forest",
    "mountain",
    "hill",
    "river",
    "lake",
    "ocean",
    "beach",
    "snow",
    "clouds",
    "sky",
    "sunset",
    "night",
    "rain",
    "fog",
    "animal",
    "dog",
    "cat",
    "bird",
    "horse",
    "cow",
    "sheep",
    "goat",
    "deer",
    "bear",
    "elephant",
    "giraffe",
    "zebra",
    "lion",
    "tiger",
    "monkey",
    "fish",
    "insect",
    "butterfly",
    "flower",
    "grass",
    "field",
    "park",
    "garden",
    "tree trunk",
    "leaf",
    "waterfall",
    "rock",
    "cliff",
    "desert",
    "sand",
    "chair",
    "couch",
    "table",
    "desk",
    "bed",
    "lamp",
    "bookshelf",
    "cabinet",
    "door",
    "window",
    "staircase",
    "kitchen",
    "bathroom",
    "toilet",
    "sink",
    "mirror",
    "refrigerator",
    "microwave",
    "oven",
    "stove",
    "dishwasher",
    "television",
    "computer",
    "laptop",
    "keyboard",
    "mouse",
    "phone",
    "camera",
    "tripod",
    "speaker",
    "headphones",
    "backpack",
    "handbag",
    "suitcase",
    "bottle",
    "cup",
    "glass",
    "plate",
    "bowl",
    "spoon",
    "fork",
    "knife",
    "food",
    "fruit",
    "vegetable",
    "bread",
    "pizza",
    "burger",
    "sandwich",
    "salad",
    "cake",
    "donut",
    "ice cream",
    "sports ball",
    "soccer ball",
    "basketball",
    "tennis racket",
    "baseball bat",
    "skateboard",
    "surfboard",
    "ski",
    "snowboard",
    "helmet",
    "gloves",
    "shoe",
    "shirt",
    "pants",
    "dress",
    "coat",
    "hat",
    "umbrella",
    "watch",
    "clock",
    "book",
    "notebook",
    "paper",
    "pen",
    "pencil",
    "tool",
    "hammer",
    "wrench",
    "screwdriver",
    "drill",
    "ladder",
    "sign",
    "billboard",
    "poster",
    "logo",
    "statue",
    "fountain",
    "bridge support",
    "streetlight",
    "trash can",
    "bench",
    "fence",
    "gate",
    "wall",
    "floor",
    "ceiling",
    "stairs",
    "corridor",
    "hallway",
    "classroom",
    "office",
    "conference room",
    "store",
    "market",
    "restaurant",
    "cafe",
    "bar",
    "kitchen counter",
    "countertop",
    "road sign",
    "vehicle",
    "engine",
    "wheel",
    "tire",
    "truck trailer",
    "pickup truck",
    "taxi",
    "bus stop",
    "train station",
    "airport",
    "runway",
    "harbor",
    "pier",
    "boat dock",
    "bridge railing",
    "traffic cone",
    "construction",
    "crane",
    "bulldozer",
    "excavator",
    "pavement",
    "asphalt",
    "gravel",
    "curb",
    "sidewalk curb",
    "drone",
    "bicycle wheel",
    "motorcycle helmet",
    "bus lane",
    "bike lane",
    "railroad",
    "railway",
    "rail tracks",
    "tunnel entrance",
    "overhead sign",
    "gas station",
    "fuel pump",
    "shopfront",
    "storefront",
    "awning",
    "parking garage",
    "city skyline",
    "street scene",
    "landscape",
    "portrait",
    "indoor scene",
    "outdoor scene",
]


def load_labels(path: str | None = None) -> list[str]:
    if path and os.path.exists(path):
        labels: list[str] = []
        with open(path, encoding="utf-8") as f:
            for line in f:
                name = line.strip()
                if not name or name.startswith("#"):
                    continue
                labels.append(name)
        if labels:
            return labels
    return DEFAULT_LABELS
