"""Knowledge distillation pipeline: two-stage compression chain.

**Stage 1 (Gemma/DINOv3 → ViT-S/14)**

The teacher is the SSL fine-tuned DINOv3 ViT-B/14 backbone (or a GemmaVisionTeacher
wrapping the Gemma 4 vision encoder for maximum-hydration runs).  The student is
DINOv2 ViT-S/14 (~22M params, 384-dim) vs the teacher's ViT-B/14 (~86M, 768-dim).
After Stage 1 the student is ~4× smaller and ~2× faster.  Requires ≥24 GB VRAM when
using the Gemma teacher; ~8 GB with the DINOv3 teacher.

Training uses Relational Knowledge Distillation with Distance + Angle losses (RKD-DA)
plus a KoLeo spread regulariser and an optional cosine anchor loss:

    L = λ_D · L_RKD_dist  +  λ_A · L_RKD_angle  +  λ_kd · L_cosine  +  λ_koleo · L_KoLeo

RKD-DA preserves pairwise neighbourhood topology in the student embedding space,
which directly optimises retrieval Recall@K.  Defaults: λ_D=25, λ_A=50 (paper values).

A temporary projection head (Linear s_dim→t_dim, orthogonal init) aligns the student
output space with the teacher's during training; it is discarded after training.

**Stage 2 (ViT-S/14 → EfficientViT-B1)**

Optional second compression hop for edge deployment.  The Stage 1 ViT-S/14 student
becomes the Stage 2 teacher; EfficientViT-B1 (~9M params, 384-dim) is the student.
Both teacher and student are 384-dim so RKD-A provides no benefit — Stage 2 uses
RKD-D + KoLeo only (λ_A=0).  Requires only ~2 GB VRAM.

Use :func:`run_distillation_efficientvit` for Stage 2.  The ``stage`` field in
:class:`DistillConfig` records which stage produced a checkpoint (1 or 2).
"""

import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from torch import Tensor
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms

from selfsuvis.pipeline.core import get_logger

from .common import (
    checkpoint_path,
    ensure_output_dir,
    epoch_checkpoint_path,
    save_backbone_checkpoint,
)

logger = get_logger(__name__)


# ── Config ────────────────────────────────────────────────────────────────────


@dataclass
class DistillConfig:
    """Hyperparameters for the distillation run."""

    student_model: str = "dinov2_vits14"  # ViT-S/14 — 22M params, 384-dim
    epochs: int = 5
    batch_size: int = 16
    lr: float = 1e-4
    weight_decay: float = 1e-4
    grad_clip: float = 1.0
    image_size: int = 224
    device: str = "cuda"
    num_workers: int = 0
    # RKD-DA loss weights (Park et al. 2019 defaults)
    lambda_rkd_d: float = 25.0  # pairwise distance preservation
    lambda_rkd_a: float = 50.0  # triplet angle preservation
    lambda_kd: float = 1.0  # cosine anchor (student proj ≈ teacher)
    lambda_koleo: float = 0.1  # KoLeo spread regulariser
    # Caption anchor: pull student embeddings toward CLIP text embeddings of
    # per-frame captions generated by Gemma/Florence. Set lambda > 0 to enable.
    lambda_caption_anchor: float = 0.0
    caption_embeddings: np.ndarray | None = None  # (N_frames, clip_dim)
    # Distillation stage (1 = Gemma/DINOv3→ViT-S/14; 2 = ViT-S/14→EfficientViT-B1)
    stage: int = 1


# ── Dataset ───────────────────────────────────────────────────────────────────


class _FrameDataset(Dataset):
    """Minimal dataset: loads frames from disk as normalised tensors."""

    def __init__(self, frame_paths: list[str], image_size: int = 224) -> None:
        self.paths = frame_paths
        self.transform = transforms.Compose(
            [
                transforms.Resize(image_size, interpolation=transforms.InterpolationMode.BICUBIC),
                transforms.CenterCrop(image_size),
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
            ]
        )

    def __len__(self) -> int:
        return len(self.paths)

    def __getitem__(self, idx: int) -> torch.Tensor:
        img = Image.open(self.paths[idx]).convert("RGB")
        return self.transform(img)


# ── RKD loss functions ────────────────────────────────────────────────────────


def _pairwise_dist(x: Tensor) -> Tensor:
    """Squared Euclidean pairwise distance matrix, clamped ≥ 0."""
    xx = (x * x).sum(dim=-1, keepdim=True)  # (B, 1)
    dist2 = xx + xx.T - 2.0 * (x @ x.T)  # (B, B)
    dist = dist2.clamp(min=1e-12).sqrt()  # (B, B)
    mask = torch.eye(dist.shape[0], device=dist.device, dtype=torch.bool)
    return dist.masked_fill(mask, 0.0)


def _mean_off_diagonal(x: Tensor) -> Tensor:
    if x.shape[0] < 2:
        return x.new_tensor(1.0)
    mask = ~torch.eye(x.shape[0], device=x.device, dtype=torch.bool)
    vals = x.masked_select(mask)
    if vals.numel() == 0:
        return x.new_tensor(1.0)
    return vals.mean().clamp(min=1e-8)


def rkd_distance_loss(t: Tensor, s: Tensor) -> Tensor:
    """RKD-D: preserve pairwise distance structure (Huber loss on normalised distances).

    Both t and s should be L2-normalised (B, D) tensors.
    """
    td = _pairwise_dist(t)
    sd = _pairwise_dist(s)
    # Normalise by mean so scale differences don't dominate
    td = td / _mean_off_diagonal(td)
    sd = sd / _mean_off_diagonal(sd)
    return F.huber_loss(sd, td, delta=1.0)


def rkd_angle_loss(t: Tensor, s: Tensor) -> Tensor:
    """RKD-A: preserve triplet angle structure (Huber loss on cosine angles).

    For each vertex j and all pairs (i, k), the angle ∠(i, j, k) is the cosine
    similarity between the unit vectors (j→i) and (j→k).

    Both t and s should be L2-normalised (B, D) tensors.
    Memory: O(B² · D) for diff tensors, O(B³) for angle tensor — fine for B≤64.
    """
    # Difference vectors: td[i,j] = t[i] - t[j]  →  (B, B, D)
    td = t.unsqueeze(1) - t.unsqueeze(0)  # (B, B, D)
    sd = s.unsqueeze(1) - s.unsqueeze(0)
    td_n = F.normalize(td, dim=-1, eps=1e-8)
    sd_n = F.normalize(sd, dim=-1, eps=1e-8)
    # angle[i, j, k] = cos(∠ i-j-k) = td_n[i,j] · td_n[k,j]
    # einsum: ijd, kjd -> ijk
    t_angle = torch.einsum("ijd,kjd->ijk", td_n, td_n)  # (B, B, B)
    s_angle = torch.einsum("ijd,kjd->ijk", sd_n, sd_n)
    return F.huber_loss(s_angle, t_angle, delta=1.0)


def koleo_loss(s: Tensor) -> Tensor:
    """KoLeo regulariser: maximise minimum pairwise distance → prevent collapse.

    L_KoLeo = -1/n · Σ log ||s_i − nn(s_i)||

    s should be L2-normalised (B, D).
    """
    if s.shape[0] < 2:
        return s.new_tensor(0.0)
    dist = _pairwise_dist(s)  # (B, B)
    mask = torch.eye(s.shape[0], device=s.device, dtype=torch.bool)
    dist = dist.masked_fill(mask, float("inf"))
    nn_dist = dist.min(dim=-1).values.clamp(min=1e-8)  # (B,)
    return -torch.log(nn_dist).mean()


def _module_forward_dtype(module: torch.nn.Module) -> torch.dtype:
    """Infer a safe floating dtype for dummy forwards against *module*."""
    for param in module.parameters():
        if torch.is_floating_point(param):
            return param.dtype
    for buffer in module.buffers():
        if torch.is_floating_point(buffer):
            return buffer.dtype
    return torch.float32


def _module_dummy_input(
    module: torch.nn.Module,
    *,
    image_size: int,
    device: str,
) -> Tensor:
    """Create a dummy BCHW image tensor matching *module*'s expected float dtype."""
    return torch.zeros(
        1,
        3,
        image_size,
        image_size,
        device=device,
        dtype=_module_forward_dtype(module),
    )


# ── Recall@1 metric ───────────────────────────────────────────────────────────


@torch.no_grad()
def recall_at_1(teacher_embs: Tensor, student_embs: Tensor) -> float:
    """Fraction of samples whose nearest neighbour in student space matches teacher space.

    Both inputs should be L2-normalised (N, D) tensors.
    Returns a float in [0, 1]; higher = student preserved teacher's local structure.
    """
    t_sim = teacher_embs @ teacher_embs.T
    t_sim.fill_diagonal_(float("-inf"))
    t_nn = t_sim.argmax(dim=-1)

    s_sim = student_embs @ student_embs.T
    s_sim.fill_diagonal_(float("-inf"))
    s_nn = s_sim.argmax(dim=-1)

    return (t_nn == s_nn).float().mean().item()


def _should_update_best_checkpoint(
    *,
    best_recall: float,
    best_loss: float,
    candidate_recall: float,
    candidate_loss: float,
) -> bool:
    """Prefer better retrieval structure; use loss only as a tiebreaker."""
    return candidate_recall > best_recall + 1e-6 or (
        abs(candidate_recall - best_recall) <= 1e-6 and candidate_loss < best_loss
    )


# ── Distiller ─────────────────────────────────────────────────────────────────


class KnowledgeDistiller:
    """Distils a large teacher backbone into a smaller student backbone using RKD-DA.

    Args:
        teacher:  Fine-tuned PyTorch backbone in eval mode (weights frozen).
        config:   DistillConfig hyperparameters.
    """

    def __init__(self, teacher: torch.nn.Module, config: DistillConfig) -> None:
        self.config = config
        self.device = config.device

        # Teacher — frozen for the entire distillation run
        self.teacher = teacher.to(self.device).eval()
        for p in self.teacher.parameters():
            p.requires_grad_(False)

        # Infer teacher output dimension
        with torch.no_grad():
            _dummy = _module_dummy_input(
                self.teacher,
                image_size=config.image_size,
                device=self.device,
            )
            self._t_dim: int = int(self.teacher(_dummy).shape[-1])
        logger.info("Teacher: %s  dim=%d (frozen)", type(teacher).__name__, self._t_dim)

        # Student backbone (pretrained, smaller)
        self.student = self._load_student()
        with torch.no_grad():
            _student_dummy = _module_dummy_input(
                self.student,
                image_size=config.image_size,
                device=self.device,
            )
            self._s_dim: int = int(self.student(_student_dummy).shape[-1])
        logger.info("Student: %s  dim=%d (trainable)", config.student_model, self._s_dim)

        # Projection head (used only during training, then discarded)
        self._proj = nn.Linear(self._s_dim, self._t_dim, bias=False).to(self.device)
        nn.init.orthogonal_(self._proj.weight)

        # Param counts for compression ratio
        self._teacher_params = sum(p.numel() for p in self.teacher.parameters())
        self._student_params = sum(p.numel() for p in self.student.parameters())
        compression = self._teacher_params / max(self._student_params, 1)
        logger.info(
            "Compression: %.1f× (teacher=%dM, student=%dM)",
            compression,
            self._teacher_params // 1_000_000,
            self._student_params // 1_000_000,
        )

    # ── Private helpers ───────────────────────────────────────────────────────

    def _load_student(self) -> torch.nn.Module:
        if self.config.student_model.startswith("efficientvit_"):
            try:
                from selfsuvis.models.efficientvit_model import EfficientViTEmbedder
            except ImportError as exc:
                raise ImportError(
                    "timm is required for EfficientViT student: pip install timm"
                ) from exc
            logger.info("Loading student backbone: EfficientViT (via EfficientViTEmbedder) …")
            embedder = EfficientViTEmbedder()
            return embedder.as_torch_backbone().to(self.device).train()
        from selfsuvis.models.dino_model import hub_load_dino

        logger.info("Loading student backbone: %s …", self.config.student_model)
        model = hub_load_dino(self.config.student_model, pretrained=True)
        return model.to(self.device).train()

    def _forward_teacher(self, batch: torch.Tensor) -> torch.Tensor:
        """Run teacher with AMP on CUDA; returns normalised float32 embeddings.

        NaN values in the teacher output (e.g. from Gemma vision encoder on
        edge-case inputs) are replaced with 0.0 before L2 normalisation so that
        the RKD loss remains finite throughout training.
        """
        with torch.no_grad():
            if self.config.device == "cuda":
                with torch.amp.autocast("cuda"):
                    t = self.teacher(batch)
            else:
                t = self.teacher(batch)
        t = torch.nan_to_num(t.float(), nan=0.0)  # guard against Gemma NaN outputs
        return F.normalize(t, dim=-1)  # (B, t_dim)

    def _forward_student(self, batch: torch.Tensor) -> tuple[Tensor, Tensor]:
        """Run student + projection head with AMP; returns normalised embeddings."""
        if self.config.device == "cuda":
            with torch.amp.autocast("cuda"):
                s = self.student(batch)
        else:
            s = self.student(batch)
        s_proj = self._proj(s.float())  # (B, t_dim)
        return F.normalize(s_proj, dim=-1), F.normalize(s.float(), dim=-1)

    @torch.no_grad()
    def _collect_embeddings(self, loader: DataLoader) -> tuple[Tensor, Tensor]:
        """Collect all teacher and (raw, pre-proj) student embeddings for Recall@1."""
        self.student.eval()
        t_embs, s_embs = [], []
        for batch in loader:
            batch = batch.to(self.device)
            t_embs.append(self._forward_teacher(batch))
            if self.config.device == "cuda":
                with torch.amp.autocast("cuda"):
                    s = self.student(batch)
            else:
                s = self.student(batch)
            s_embs.append(F.normalize(s.float(), dim=-1))
        self.student.train()
        return torch.cat(t_embs, dim=0), torch.cat(s_embs, dim=0)

    # ── Public API ────────────────────────────────────────────────────────────

    def distill(
        self,
        frame_paths: list[str],
        checkpoint_dir: Path,
    ) -> dict[str, Any]:
        """Train the student with RKD-DA + KoLeo + cosine anchor and save checkpoints.

        Args:
            frame_paths:     Absolute paths to training frames.
            checkpoint_dir:  Directory to write per-epoch + best checkpoints.

        Returns:
            dict with keys: best_path, best_loss, loss_history, loss_components,
                            recall_history, best_recall, compression_ratio,
                            elapsed, student_model, student_dim, teacher_dim.
        """
        cfg = self.config
        checkpoint_dir = ensure_output_dir(checkpoint_dir)

        dataset = _FrameDataset(frame_paths, cfg.image_size)
        loader = DataLoader(
            dataset,
            batch_size=cfg.batch_size,
            shuffle=True,
            num_workers=cfg.num_workers,
            drop_last=len(dataset) > cfg.batch_size,
            pin_memory=(cfg.device == "cuda"),
        )
        # Separate eval loader (no shuffle, no drop_last) for Recall@1
        eval_loader = DataLoader(
            dataset,
            batch_size=cfg.batch_size,
            shuffle=False,
            num_workers=cfg.num_workers,
            pin_memory=(cfg.device == "cuda"),
        )

        trainable = list(self.student.parameters()) + list(self._proj.parameters())
        optimizer = torch.optim.AdamW(trainable, lr=cfg.lr, weight_decay=cfg.weight_decay)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer,
            T_max=cfg.epochs,
            eta_min=cfg.lr * 0.1,
        )

        best_loss = float("inf")
        best_recall = float("-inf")
        best_path = checkpoint_path(checkpoint_dir, "student_best.pt")
        loss_history: list[float] = []
        recall_history: list[float] = []
        loss_components: dict[str, list[float]] = {
            "rkd_d": [],
            "rkd_a": [],
            "cosine": [],
            "koleo": [],
            "caption": [],
        }

        # Caption anchor tensors — one per frame, aligned with dataset order
        _cap_anchors: torch.Tensor | None = None
        if (
            cfg.lambda_caption_anchor > 0
            and cfg.caption_embeddings is not None
            and len(cfg.caption_embeddings) > 0
        ):
            _cap_np = cfg.caption_embeddings
            if len(_cap_np) == len(dataset):
                _cap_anchors = torch.from_numpy(_cap_np.astype(np.float32)).to(self.device)
                logger.info(
                    "Caption anchor loss enabled: λ=%.2f  anchors=%d  dim=%d",
                    cfg.lambda_caption_anchor,
                    len(_cap_np),
                    _cap_np.shape[1],
                )
            else:
                logger.warning(
                    "Caption anchor count (%d) != frame count (%d) — disabling anchor loss",
                    len(_cap_np),
                    len(dataset),
                )
        t0 = time.time()

        for epoch in range(1, cfg.epochs + 1):
            ep_losses: dict[str, list[float]] = {k: [] for k in loss_components}
            ep_total: list[float] = []
            self.student.train()
            self._proj.train()

            for batch_idx, batch in enumerate(loader):
                batch = batch.to(self.device)

                t_emb = self._forward_teacher(batch)  # (B, t_dim)
                s_proj, s_raw = self._forward_student(batch)  # (B, t_dim), (B, s_dim)

                # ── Loss components ───────────────────────────────────────────
                l_rkd_d = rkd_distance_loss(t_emb, s_proj)
                l_rkd_a = rkd_angle_loss(t_emb, s_proj)
                l_cosine = (1.0 - (s_proj * t_emb).sum(dim=-1)).mean()
                l_koleo = koleo_loss(s_raw)

                loss = (
                    cfg.lambda_rkd_d * l_rkd_d
                    + cfg.lambda_rkd_a * l_rkd_a
                    + cfg.lambda_kd * l_cosine
                    + cfg.lambda_koleo * l_koleo
                )

                # ── Caption anchor loss ───────────────────────────────────────
                l_caption = torch.tensor(0.0, device=self.device)
                if _cap_anchors is not None and cfg.lambda_caption_anchor > 0:
                    # Align caption anchors to this batch by dataset index
                    start = batch_idx * cfg.batch_size
                    end = min(start + batch.shape[0], len(_cap_anchors))
                    if end > start:
                        cap_batch = _cap_anchors[start:end]  # (B', clip_dim)
                        s_for_cap = s_raw[: end - start]  # (B', s_dim)
                        # Project student to caption dim if dims differ
                        if not hasattr(self, "_cap_proj"):
                            self._cap_proj = nn.Linear(
                                s_raw.shape[1], cap_batch.shape[1], bias=False
                            ).to(self.device)
                            nn.init.orthogonal_(self._cap_proj.weight)
                        s_cap_proj = F.normalize(self._cap_proj(s_for_cap.float()), dim=-1)
                        cap_norm = F.normalize(cap_batch, dim=-1)
                        l_caption = (1.0 - (s_cap_proj * cap_norm).sum(dim=-1)).mean()
                        loss = loss + cfg.lambda_caption_anchor * l_caption

                if not torch.isfinite(loss):
                    logger.warning(
                        "Non-finite distillation loss at epoch %d; "
                        "rkd_d=%s rkd_a=%s cosine=%s koleo=%s caption=%s. Skipping batch.",
                        epoch,
                        float(l_rkd_d.detach().float().cpu()),
                        float(l_rkd_a.detach().float().cpu()),
                        float(l_cosine.detach().float().cpu()),
                        float(l_koleo.detach().float().cpu()),
                        float(l_caption.detach().float().cpu()),
                    )
                    optimizer.zero_grad(set_to_none=True)
                    continue

                optimizer.zero_grad()
                loss.backward()
                nn.utils.clip_grad_norm_(self.student.parameters(), cfg.grad_clip)
                optimizer.step()

                ep_losses["rkd_d"].append(l_rkd_d.item())
                ep_losses["rkd_a"].append(l_rkd_a.item())
                ep_losses["cosine"].append(l_cosine.item())
                ep_losses["koleo"].append(l_koleo.item())
                ep_losses["caption"].append(float(l_caption.detach().cpu()))
                ep_total.append(loss.item())

            scheduler.step()

            if not ep_total:
                logger.warning(
                    "Distill %d/%d produced no valid batches; stopping early.", epoch, cfg.epochs
                )
                break

            epoch_loss = float(np.mean(ep_total))
            loss_history.append(epoch_loss)
            for k in loss_components:
                loss_components[k].append(float(np.mean(ep_losses[k])))

            # Recall@1 on full dataset (student raw dim, no proj)
            t_all, s_all = self._collect_embeddings(eval_loader)
            r1 = recall_at_1(t_all, s_all)
            recall_history.append(r1)

            cap_str = (
                f"  cap={loss_components['caption'][-1]:.4f}" if _cap_anchors is not None else ""
            )
            logger.info(
                "Distill %d/%d  total=%.4f  rkd_d=%.4f  rkd_a=%.4f  cos=%.4f  koleo=%.4f%s  R@1=%.3f",
                epoch,
                cfg.epochs,
                epoch_loss,
                loss_components["rkd_d"][-1],
                loss_components["rkd_a"][-1],
                loss_components["cosine"][-1],
                loss_components["koleo"][-1],
                cap_str,
                r1,
            )

            # Save student backbone only (no projection head)
            epoch_path = epoch_checkpoint_path(checkpoint_dir, "student", epoch)
            save_backbone_checkpoint(self.student, epoch_path)
            if _should_update_best_checkpoint(
                best_recall=best_recall,
                best_loss=best_loss,
                candidate_recall=r1,
                candidate_loss=epoch_loss,
            ):
                best_loss = epoch_loss
                best_recall = r1
                save_backbone_checkpoint(self.student, best_path)
                logger.info("  ↳ best checkpoint saved (R@1=%.3f  loss=%.4f)", r1, best_loss)

        elapsed = time.time() - t0
        compression_ratio = self._teacher_params / max(self._student_params, 1)
        logger.info(
            "Distillation complete: %.1fs | best_loss=%.4f | best_R@1=%.3f | "
            "compression=%.1f× | student=%s (dim=%d, %dM params)",
            elapsed,
            best_loss,
            max(best_recall, 0.0),
            compression_ratio,
            cfg.student_model,
            self._s_dim,
            self._student_params // 1_000_000,
        )
        return {
            "best_path": best_path,
            "best_loss": best_loss,
            "best_recall": max(best_recall, 0.0),
            "loss_history": loss_history,
            "loss_components": loss_components,
            "recall_history": recall_history,
            "compression_ratio": compression_ratio,
            "teacher_params": self._teacher_params,
            "student_params": self._student_params,
            "elapsed": elapsed,
            "student_model": cfg.student_model,
            "student_dim": self._s_dim,
            "teacher_dim": self._t_dim,
        }

    def student_backbone(self) -> torch.nn.Module:
        """Return the trained student backbone in eval mode (projection head discarded)."""
        self.student.eval()
        return self.student


# ── Top-level entry point ─────────────────────────────────────────────────────


class GemmaVisionTeacher(torch.nn.Module):
    """Wraps a loaded GemmaEmbedder as a standard nn.Module teacher for distillation.

    Extracts per-frame embeddings from the Gemma 4 multimodal vision encoder
    (mean-pooled last hidden state, L2-normalised) without running text generation.
    The LM backbone is never invoked — only the vision path.

    Usage::

        from selfsuvis.models.gemma_model import GemmaEmbedder
        embedder = GemmaEmbedder(model_id="google/gemma-4-it-2b", device="cuda")
        teacher  = GemmaVisionTeacher(embedder)
        stats    = run_distillation(teacher, frame_paths, ckpt_dir, cfg)
    """

    def __init__(self, embedder: Any) -> None:
        super().__init__()
        self._embedder = embedder
        # Expose dim so KnowledgeDistiller can infer t_dim via a dummy forward
        self._dim: int = embedder.image_dim()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Convert a (B, 3, H, W) float tensor batch → (B, dim) L2-normalised embeddings.

        Converts to PIL images, runs GemmaEmbedder.encode_images, returns as tensor.
        """
        from torchvision.transforms.functional import to_pil_image  # lazy import

        pils = [to_pil_image(img.clamp(0, 1).cpu()) for img in x]
        embs = self._embedder.encode_images(pils)  # numpy (B, dim)
        return torch.from_numpy(embs).to(x.device)

    # Note: do NOT override parameters() here.  KnowledgeDistiller freezes the
    # teacher by calling p.requires_grad_(False) on every parameter it finds via
    # the normal parameters() iterator.  Hiding parameters() would cause the
    # compression ratio to be reported as "0×" (teacher=0M) since no params
    # are enumerated.  The teacher is never passed to an optimizer anyway —
    # only student.parameters() and _proj.parameters() are added to the
    # optimizer group.


def run_distillation(
    teacher_backbone: torch.nn.Module,
    frame_paths: list[str],
    checkpoint_dir: Path,
    config: DistillConfig,
) -> dict[str, Any]:
    """Distil teacher into a smaller student and save checkpoints.

    Args:
        teacher_backbone: Fine-tuned PyTorch backbone (will be frozen).
        frame_paths:      Absolute paths to frames used for training.
        checkpoint_dir:   Directory for student checkpoints.
        config:           DistillConfig instance.

    Returns:
        dict with keys: best_path, best_loss, best_recall, loss_history,
                        loss_components, recall_history, compression_ratio,
                        elapsed, student_model, student_dim, teacher_dim, distiller.
    """
    distiller = KnowledgeDistiller(teacher_backbone, config)
    stats = distiller.distill(frame_paths, checkpoint_dir)
    return {**stats, "distiller": distiller}


def run_distillation_efficientvit(
    teacher_backbone: torch.nn.Module,
    frame_paths: list[str],
    checkpoint_dir: Path,
    config: DistillConfig | None = None,
) -> dict[str, Any]:
    """Stage 1→2 distillation: ViT-S/14 teacher → EfficientViT-B1 student.

    Uses RKD-D + KoLeo only (no RKD-A) because both teacher and student are
    384-dim — the angle-triplet loss gives no additional benefit at equal
    dimensionality.  Requires only ~2 GB VRAM (vs ≥24 GB for Stage 0→1).

    The ``student_model`` field in *config* is ignored; EfficientViT-B1 via
    timm is always loaded as the student.

    Args:
        teacher_backbone: Frozen teacher (e.g. fine-tuned DINOv3 ViT-B/14).
        frame_paths:      Absolute paths to frames for training.
        checkpoint_dir:   Directory for student checkpoints.
        config:           Optional DistillConfig override.  Defaults to
                          RKD-D only (lambda_rkd_a=0.0, lambda_koleo=0.1).

    Returns:
        Same dict as :func:`run_distillation`, plus ``student_model="efficientvit_b1"``.

    Raises:
        RuntimeError: If CUDA OOM is detected during model load or training,
            with a message indicating the VRAM requirement.
    """
    import torch as _torch

    if config is None:
        config = DistillConfig(
            student_model="efficientvit_b1",
            lambda_rkd_d=25.0,
            lambda_rkd_a=0.0,  # RKD-D only for Stage 1→2
            lambda_kd=1.0,
            lambda_koleo=0.1,
        )
    else:
        # Force RKD-A off regardless of what caller passed
        config = DistillConfig(
            **{
                **config.__dict__,
                "student_model": "efficientvit_b1",
                "lambda_rkd_a": 0.0,
            }
        )

    # ── Load EfficientViT-B1 student via timm ─────────────────────────────────
    try:
        import timm  # noqa: PLC0415
    except ImportError as exc:
        raise ImportError(
            "timm is required for EfficientViT distillation: pip install timm"
        ) from exc

    try:
        _student_timm = timm.create_model("efficientvit_b1", pretrained=True, num_classes=0)
    except RuntimeError as exc:
        _oom_msg = str(exc).lower()
        if "out of memory" in _oom_msg or "cuda out of memory" in _oom_msg:
            _free_gb = 0.0
            try:
                _free_gb = _torch.cuda.mem_get_info()[0] / 1e9
            except Exception:
                pass
            raise RuntimeError(
                f"EfficientViT Stage 1→2 requires ≥8GB VRAM; "
                f"detected {_free_gb:.1f}GB free. "
                "Try: device='cpu', or free VRAM before loading."
            ) from exc
        raise

    # Wrap the timm model as an nn.Module the distiller can use as the student.
    # KnowledgeDistiller expects student to be replaceable — we inject it by
    # subclassing and overriding __init__ so the distiller's projection head
    # is built against the correct 384-dim output.
    _student_timm = _student_timm.to(config.device)

    class _EfficientViTStudent(nn.Module):
        """Thin wrapper so KnowledgeDistiller can treat EfficientViT as a student."""

        def __init__(self, backbone: nn.Module) -> None:
            super().__init__()
            self.backbone = backbone

        def forward(self, x: _torch.Tensor) -> _torch.Tensor:
            return self.backbone(x)

    _student = _EfficientViTStudent(_student_timm)

    # Patch the distiller to use our student instead of dinov2_vits14
    distiller = KnowledgeDistiller(teacher_backbone, config)
    distiller.student = _student.to(config.device)

    # Rebuild projection head for the actual student dim (may differ from default)
    with _torch.no_grad():
        _student_dummy = _module_dummy_input(
            distiller.student,
            image_size=config.image_size,
            device=config.device,
        )
        _teacher_dummy = _module_dummy_input(
            distiller.teacher,
            image_size=config.image_size,
            device=config.device,
        )
        _s_dim = int(distiller.student(_student_dummy).shape[-1])
        _t_dim = int(distiller.teacher(_teacher_dummy).shape[-1])
    distiller._s_dim = _s_dim
    distiller._t_dim = _t_dim
    distiller._proj = nn.Linear(_s_dim, _t_dim, bias=False).to(config.device)
    nn.init.orthogonal_(distiller._proj.weight)

    try:
        stats = distiller.distill(frame_paths, checkpoint_dir)
    except RuntimeError as exc:
        _oom_msg = str(exc).lower()
        if "out of memory" in _oom_msg:
            _free_gb = 0.0
            try:
                _free_gb = _torch.cuda.mem_get_info()[0] / 1e9
            except Exception:
                pass
            raise RuntimeError(
                f"EfficientViT Stage 1→2 requires ≥8GB VRAM; detected {_free_gb:.1f}GB free."
            ) from exc
        raise

    return {**stats, "distiller": distiller, "student_model": "efficientvit_b1"}
