"""Step 03 — Gemma multimodal video analysis."""

import time
from pathlib import Path
from typing import Any

from selfsuvis.pipeline.core import settings
from selfsuvis.pipeline.core.logging import get_logger

from ..caption_helpers.frame_selection import _reduce_llm_sample_frames
from ..caption_helpers.gemma_api import (
    _gemma_analyse_frame_via_api,
    _summarise_gemma_captions_to_structured_scene,
)
from ..common import (
    _GEMMA_ANALYSIS_SAMPLE_N,
    _GEMMA_TEXT_PROBES,
    _SCENE_CHANGE_THRESH,
    _open_frame_image,
)

_log = get_logger("pipeline.local.caption")

try:
    from selfsuvis.models.dino_model import DINOEmbedder

    _HAS_DINO = True
except Exception:
    _HAS_DINO = False

try:
    from selfsuvis.models.gemma_model import GemmaEmbedder

    _HAS_GEMMA = True
except Exception:
    _HAS_GEMMA = False


def step_gemma_analysis(
    video_path: Path,
    video_id: str,
    video_name: str,
    video_dir: Path,
    frame_list: list[tuple[str, float]],
    models: dict[str, Any],
    gemma_api_url: str = "",
    gemma_api_model: str = "",
) -> dict[str, Any]:
    """Step 03: Gemma open-weight multimodal video analysis.

    Uses the local GemmaEmbedder for embedding-based analysis and, when a
    Gemma Ollama/vLLM sidecar is configured (GEMMA_API_URL), also runs
    generative per-frame scene description.

    Analyses performed:
    1. Generative frame descriptions via Gemma sidecar (if GEMMA_API_URL set)
    2. Scene change detection — consecutive-frame cosine distance
    3. Semantic scene clustering — greedy cosine-based grouping
    4. Zero-shot scene classification — text probe vs frame embedding scores
    5. Cross-modal text -> frame retrieval — nearest-neighbour in Gemma space
    6. Temporal video embedding — mean-pool of all frame embeddings
    7. Gemma vs CLIP embedding comparison — MNN@k and mean pairwise cosine sim
    8. Gemma vs DINOv3 embedding comparison — MNN@k and mean pairwise cosine sim

    Skipped gracefully when GemmaEmbedder is unavailable and no sidecar is set.
    Writes ``gemma_analysis.md`` to *video_dir*.
    """
    import numpy as np

    from ..report import _write_gemma_captions_md, write_gemma_analysis_md

    result: dict[str, Any] = {"skipped": True, "reason": ""}

    effective_api_url = gemma_api_url or settings.GEMMA_API_URL
    effective_api_model = gemma_api_model or settings.GEMMA_API_MODEL
    effective_timeout = float(settings.GEMMA_API_TIMEOUT_SEC)

    _clip_model = models.get("clip")
    has_local = _clip_model is not None
    _embedder_name = (
        "GemmaEmbedder"
        if (_HAS_GEMMA and isinstance(_clip_model, GemmaEmbedder))
        else type(_clip_model).__name__
        if _clip_model is not None
        else "none"
    )
    has_sidecar = bool(effective_api_url)

    if not has_local and not has_sidecar:
        result["reason"] = "No embedder available and GEMMA_API_URL not set"
        _log.info("  Gemma analysis skipped: %s", result["reason"])
        return result

    t0 = time.time()

    n_avail = len(frame_list)
    n_sample = min(
        int(settings.GEMMA_ANALYSIS_MAX_SAMPLE_FRAMES), _GEMMA_ANALYSIS_SAMPLE_N, n_avail
    )
    step = max(1, n_avail // max(1, n_sample))
    sample_frames = frame_list[::step][:n_sample]
    sample_frames = _reduce_llm_sample_frames(sample_frames, max_frames=n_sample)
    sample_images = [_open_frame_image(fp) for fp, _ in sample_frames]
    sample_paths = [fp for fp, _ in sample_frames]
    sample_ts = [t for _, t in sample_frames]
    n = len(sample_images)
    _log.info("  Gemma analysis: %d sampled frames (from %d total)", n, n_avail)

    task_results: dict[str, Any] = {}

    # 1. Generative per-frame analysis via Ollama/vLLM sidecar
    gemma_captions: list[dict[str, Any]] = []
    if has_sidecar:
        _log.info(
            "Generative scene analysis via sidecar (url=%s  model=%s  frames=%d) ...",
            effective_api_url,
            effective_api_model,
            n,
        )
        for idx, (fp, t_sec) in enumerate(sample_frames):
            desc = _gemma_analyse_frame_via_api(
                fp,
                effective_api_url,
                effective_api_model,
                effective_timeout,
                video_dir=video_dir,
            )
            gemma_captions.append({"frame_path": fp, "t_sec": t_sec, "description": desc})
            if (idx + 1) % 10 == 0:
                _log.info("    ... %d/%d frames analysed via Gemma sidecar", idx + 1, n)
        described = sum(1 for c in gemma_captions if c.get("description"))
        _log.info("Generative descriptions: %d/%d frames", described, n)
        task_results["generative_descriptions"] = {
            "description": "Per-frame scene description generated by Gemma sidecar",
            "n_frames": n,
            "described_count": described,
            "model": effective_api_model,
            "captions": gemma_captions,
        }
        _write_gemma_captions_md(
            video_dir / "gemma_captions.md",
            video_name,
            effective_api_model,
            gemma_captions,
        )
        structured_scene = _summarise_gemma_captions_to_structured_scene(
            gemma_captions,
            effective_api_url,
            effective_api_model,
            effective_timeout,
        )
        task_results["structured_scene_summary"] = structured_scene
    else:
        task_results["generative_descriptions"] = {
            "description": "Skipped — GEMMA_API_URL not configured",
            "skipped": True,
        }
        structured_scene = {}

    if not has_local:
        _log.info("Skipping embedding analyses (no embedder loaded)")
        text_query_results: list[dict[str, Any]] = []
        dino_comparison: dict[str, Any] = {"available": False, "reason": "no embedder loaded"}
        clip_comparison: dict[str, Any] = {"available": False, "reason": "GemmaEmbedder not loaded"}
        elapsed = time.time() - t0
        write_gemma_analysis_md(
            video_dir / "gemma_analysis.md",
            video_name,
            effective_api_model or settings.GEMMA_MODEL_ID,
            n,
            task_results,
            dino_comparison,
            text_query_results,
            elapsed,
            clip_comparison=clip_comparison,
        )
        result.update(
            {
                "skipped": False,
                "n_frames": n,
                "task_results": task_results,
                "dino_comparison": dino_comparison,
                "clip_comparison": clip_comparison,
                "elapsed_sec": elapsed,
                "structured_scene": structured_scene,
            }
        )
        return result

    gemma: GemmaEmbedder = models["clip"]  # type: ignore[assignment]
    _log.info("Embedding analyses using %s", _embedder_name)

    # 2. Scene change detection via consecutive-frame cosine distance
    gemma_embeds: np.ndarray | None = None
    try:
        _log.info("Scene change detection ...")
        gemma_embeds = gemma.encode_images(sample_images)
        changes = []
        for i in range(1, n):
            cos_sim = float(np.dot(gemma_embeds[i - 1], gemma_embeds[i]))
            distance = 1.0 - cos_sim
            if distance >= _SCENE_CHANGE_THRESH:
                changes.append({"frame_idx": i, "t_sec": sample_ts[i], "distance": distance})
        task_results["scene_change_detection"] = {
            "description": "Consecutive-frame cosine distance > threshold",
            "n_changes": len(changes),
            "threshold": _SCENE_CHANGE_THRESH,
            "changes": changes,
        }
        _log.info("Scene changes detected: %d", len(changes))
    except Exception as exc:
        task_results["scene_change_detection"] = {"error": str(exc)}
        _log.warning("Scene change detection failed: %s", exc)

    # 3. Greedy cosine-based scene clustering
    try:
        _log.info("Semantic scene clustering ...")
        cl_embeds = gemma_embeds if gemma_embeds is not None else gemma.encode_images(sample_images)
        sim_mat = np.dot(cl_embeds, cl_embeds.T)
        labels = [-1] * n
        cluster_id = 0
        for i in range(n):
            if labels[i] != -1:
                continue
            labels[i] = cluster_id
            for j in range(i + 1, n):
                if labels[j] == -1 and sim_mat[i, j] > (1.0 - _SCENE_CHANGE_THRESH):
                    labels[j] = cluster_id
            cluster_id += 1
        task_results["scene_clustering"] = {
            "description": "Greedy scene grouping by cosine similarity",
            "n_clusters": cluster_id,
            "n_frames": n,
            "mean_cluster_size": round(n / max(1, cluster_id), 2),
        }
        _log.info("Scene clusters: %d from %d frames", cluster_id, n)
    except Exception as exc:
        task_results["scene_clustering"] = {"error": str(exc)}
        _log.warning("Scene clustering failed: %s", exc)

    # 4. Zero-shot scene classification via text probe matching
    try:
        _log.info("Zero-shot scene classification (%d probes) ...", len(_GEMMA_TEXT_PROBES))
        clf_frame = gemma_embeds if gemma_embeds is not None else gemma.encode_images(sample_images)
        clf_text = gemma.encode_texts(_GEMMA_TEXT_PROBES)
        clf_scores = np.dot(clf_frame, clf_text.T)
        from collections import Counter

        top_cats: list[str] = [_GEMMA_TEXT_PROBES[int(np.argmax(clf_scores[i]))] for i in range(n)]
        cat_dist = dict(Counter(top_cats).most_common(5))
        task_results["scene_classification"] = {
            "description": f"Zero-shot classification against {len(_GEMMA_TEXT_PROBES)} scene categories",
            "n_frames": n,
            "category_distribution": cat_dist,
        }
        _log.info("Top category: %s", next(iter(cat_dist)) if cat_dist else "---")
    except Exception as exc:
        task_results["scene_classification"] = {"error": str(exc)}
        _log.warning("Zero-shot classification failed: %s", exc)

    # 5. Cross-modal text -> frame retrieval
    text_query_results = []
    try:
        _log.info("Cross-modal text->frame retrieval (%d probes) ...", len(_GEMMA_TEXT_PROBES))
        doc_embeds = (
            gemma_embeds if gemma_embeds is not None else gemma.encode_images(sample_images)
        )
        query_embeds = gemma.encode_texts(_GEMMA_TEXT_PROBES)
        tq_scores = np.dot(query_embeds, doc_embeds.T)
        for q_idx, query in enumerate(_GEMMA_TEXT_PROBES):
            top_idxs = list(np.argsort(-tq_scores[q_idx])[:3])
            text_query_results.append(
                {
                    "query": query,
                    "top_results": [
                        {
                            "frame_path": sample_paths[i],
                            "t_sec": sample_ts[i],
                            "score": float(tq_scores[q_idx, i]),
                        }
                        for i in top_idxs
                    ],
                }
            )
        task_results["cross_modal_retrieval"] = {
            "description": "Text probes matched against Gemma frame embeddings",
            "n_queries": len(_GEMMA_TEXT_PROBES),
        }
    except Exception as exc:
        task_results["cross_modal_retrieval"] = {"error": str(exc)}
        _log.warning("Cross-modal retrieval failed: %s", exc)

    # 6. Temporal video embedding (mean-pool all frames)
    try:
        _log.info("Temporal video embedding ...")
        if hasattr(gemma, "encode_images_temporal"):
            vid_embed = gemma.encode_images_temporal(sample_images)
        else:
            import torch as _torch

            _feats = gemma.encode_images(sample_images)
            _t = _torch.from_numpy(_feats).mean(dim=0, keepdim=True)
            vid_embed = _torch.nn.functional.normalize(_t, dim=-1)
        task_results["temporal_embedding"] = {
            "description": f"Mean-pool of {n} frame embeddings -> single video-level vector",
            "dim": int(vid_embed.shape[1]),
            "n_frames": n,
        }
        _log.info("Temporal embedding dim=%d", vid_embed.shape[1])
    except Exception as exc:
        task_results["temporal_embedding"] = {"error": str(exc)}
        _log.warning("Temporal embedding failed: %s", exc)

    # 7. Gemma vs CLIP comparison — skip when the main embedder IS CLIP (trivial)
    clip_comparison: dict[str, Any] = {"available": False}
    from selfsuvis.models.openclip_model import OpenCLIPEmbedder as _CLIPModel

    _main_is_clip = isinstance(gemma, _CLIPModel)
    if _main_is_clip:
        clip_comparison = {
            "available": False,
            "reason": "main embedder is OpenCLIP — comparison skipped (self vs self)",
        }
        _log.info("  [Gemma vs CLIP] Skipped — main embedder is already OpenCLIP")
    else:
        try:
            _log.info("  [Gemma vs CLIP] Loading temporary OpenCLIP ViT-B-16 ...")
            temp_clip = _CLIPModel()
            clip_frame = temp_clip.encode_images(sample_images)
            g_e = gemma_embeds if gemma_embeds is not None else gemma.encode_images(sample_images)
            g_sim_c = np.dot(g_e, g_e.T)
            c_sim = np.dot(clip_frame, clip_frame.T)
            mask_c = ~np.eye(n, dtype=bool)
            mean_cossim_gemma_c = float(np.mean(g_sim_c[mask_c]))
            mean_cossim_clip = float(np.mean(c_sim[mask_c]))
            k_c = min(5, n - 1)
            mnn_c = 0
            for i in range(n):
                gr = g_sim_c[i].copy()
                gr[i] = -2.0
                cr = c_sim[i].copy()
                cr[i] = -2.0
                mnn_c += len(
                    set(np.argsort(-gr)[:k_c].tolist()) & set(np.argsort(-cr)[:k_c].tolist())
                )
            mnn_rate_c = mnn_c / (n * k_c)
            clip_comparison = {
                "available": True,
                "n_frames": n,
                "k": k_c,
                "mnn_rate": mnn_rate_c,
                "mean_cossim_gemma": mean_cossim_gemma_c,
                "mean_cossim_clip": mean_cossim_clip,
            }
            _log.info(
                "  [Gemma vs CLIP] MNN@%d=%.3f  mean_cossim: Gemma=%.4f  CLIP=%.4f",
                k_c,
                mnn_rate_c,
                mean_cossim_gemma_c,
                mean_cossim_clip,
            )
            try:
                import torch as _t

                _bb = getattr(temp_clip, "model", None)
                if _bb is not None:
                    _bb.cpu()
            except Exception:
                pass
            del temp_clip, clip_frame
        except Exception as exc:
            clip_comparison = {"available": False, "reason": str(exc)}
            _log.warning("  [Gemma vs CLIP] comparison failed: %s", exc)

    # 8. Gemma vs DINOv3 comparison
    dino_comparison: dict[str, Any] = {"available": False}
    if _HAS_DINO and n > 1:
        try:
            _log.info("  [Gemma vs DINOv3] Loading temporary DINOv3 ViT-B/14 ...")
            temp_dino = DINOEmbedder("dinov3_vitb14")
            dino_embeds = temp_dino.encode_images(sample_images)
            g_e = gemma_embeds if gemma_embeds is not None else gemma.encode_images(sample_images)
            g_sim_d = np.dot(g_e, g_e.T)
            d_sim = np.dot(dino_embeds, dino_embeds.T)
            mask_d = ~np.eye(n, dtype=bool)
            mean_cossim_gemma_d = float(np.mean(g_sim_d[mask_d]))
            mean_cossim_dino = float(np.mean(d_sim[mask_d]))
            k_d = min(5, n - 1)
            mnn_d = 0
            for i in range(n):
                gr = g_sim_d[i].copy()
                gr[i] = -2.0
                dr = d_sim[i].copy()
                dr[i] = -2.0
                mnn_d += len(
                    set(np.argsort(-gr)[:k_d].tolist()) & set(np.argsort(-dr)[:k_d].tolist())
                )
            mnn_rate_d = mnn_d / (n * k_d)
            dino_comparison = {
                "available": True,
                "n_frames": n,
                "k": k_d,
                "mnn_rate": mnn_rate_d,
                "mean_cossim_gemma": mean_cossim_gemma_d,
                "mean_cossim_dino": mean_cossim_dino,
            }
            _log.info(
                "  [Gemma vs DINOv3] MNN@%d=%.3f  mean_cossim: Gemma=%.4f  DINO=%.4f",
                k_d,
                mnn_rate_d,
                mean_cossim_gemma_d,
                mean_cossim_dino,
            )
            try:
                import torch as _t

                _bb = getattr(temp_dino, "model", None)
                if _bb is not None:
                    _bb.cpu()
            except Exception:
                pass
            del temp_dino, dino_embeds
        except Exception as exc:
            dino_comparison = {"available": False, "reason": str(exc)}
            _log.warning("  [Gemma vs DINOv3] comparison failed: %s", exc)
    else:
        dino_comparison["reason"] = (
            "DINOv3 not available" if not _HAS_DINO else "too few frames for comparison"
        )

    elapsed = time.time() - t0

    write_gemma_analysis_md(
        video_dir / "gemma_analysis.md",
        video_name,
        effective_api_model or settings.GEMMA_MODEL_ID,
        n,
        task_results,
        dino_comparison,
        text_query_results,
        elapsed,
        clip_comparison=clip_comparison,
    )

    result.update(
        {
            "skipped": False,
            "n_frames": n,
            "task_results": task_results,
            "dino_comparison": dino_comparison,
            "clip_comparison": clip_comparison,
            "elapsed_sec": elapsed,
            "structured_scene": structured_scene,
        }
    )
    return result
